//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFplaySharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Licenses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Licenses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFplaySharp.Licenses", typeof(Licenses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is free software; you can redistribute it and/or modify
        ///it under the terms of the GNU General Public License as published by
        ///the Free Software Foundation; either version 2 of the License, or
        ///(at your option) any later version.
        ///
        ///{0} is distributed in the hope that it will be useful,
        ///but WITHOUT ANY WARRANTY; without even the implied warranty of
        ///MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        ///GNU General Public License for more details.
        ///
        ///You should have received a copy of the GNU G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GPLv2 {
            get {
                return ResourceManager.GetString("GPLv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is free software; you can redistribute it and/or modify
        ///it under the terms of the GNU General Public License as published by
        ///the Free Software Foundation; either version 3 of the License, or
        ///(at your option) any later version.
        ///
        ///{0} is distributed in the hope that it will be useful,
        ///but WITHOUT ANY WARRANTY; without even the implied warranty of
        ///MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        ///GNU General Public License for more details.
        ///
        ///You should have received a copy of the GNU G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GPLv3 {
            get {
                return ResourceManager.GetString("GPLv3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is free software; you can redistribute it and/or
        ///modify it under the terms of the GNU Lesser General Public
        ///License as published by the Free Software Foundation; either
        ///version 2.1 of the License, or (at your option) any later version.
        ///
        ///{0} is distributed in the hope that it will be useful,
        ///but WITHOUT ANY WARRANTY; without even the implied warranty of
        ///MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
        ///Lesser General Public License for more details.
        ///
        ///You should have received a c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LGPLv2 {
            get {
                return ResourceManager.GetString("LGPLv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is free software; you can redistribute it and/or modify
        ///it under the terms of the GNU Lesser General Public License as published by
        ///the Free Software Foundation; either version 3 of the License, or
        ///(at your option) any later version.
        ///
        ///{0} is distributed in the hope that it will be useful,
        ///but WITHOUT ANY WARRANTY; without even the implied warranty of
        ///MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        ///GNU Lesser General Public License for more details.
        ///
        ///You should have received a cop [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LGPLv3 {
            get {
                return ResourceManager.GetString("LGPLv3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version of {0} has nonfree parts compiled in.
        ///Therefore it is not legally redistributable..
        /// </summary>
        internal static string NonFree {
            get {
                return ResourceManager.GetString("NonFree", resourceCulture);
            }
        }
    }
}
