namespace FFmpegSharp
{
    public enum AVIODirEntryType
    {
        AVIO_ENTRY_UNKNOWN,
        AVIO_ENTRY_BLOCK_DEVICE,
        AVIO_ENTRY_CHARACTER_DEVICE,
        AVIO_ENTRY_DIRECTORY,
        AVIO_ENTRY_NAMED_PIPE,
        AVIO_ENTRY_SYMBOLIC_LINK,
        AVIO_ENTRY_SOCKET,
        AVIO_ENTRY_FILE,
        AVIO_ENTRY_SERVER,
        AVIO_ENTRY_SHARE,
        AVIO_ENTRY_WORKGROUP,
    }
}
