namespace FFmpegSharp
{
    public enum AVMatrixEncoding
    {
        AV_MATRIX_ENCODING_NONE,
        AV_MATRIX_ENCODING_DOLBY,
        AV_MATRIX_ENCODING_DPLII,
        AV_MATRIX_ENCODING_DPLIIX,
        AV_MATRIX_ENCODING_DPLIIZ,
        AV_MATRIX_ENCODING_DOLBYEX,
        AV_MATRIX_ENCODING_DOLBYHEADPHONE,
        AV_MATRIX_ENCODING_NB,
    }
}
