// Copyright (c) 2021-2023 Ronald van Manen
//
// This file is part of FFmpegSharp.
//
// FFmpegSharp is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// FFmpegSharp is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with FFmpegSharp; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

namespace FFmpegSharp
{
    public enum AVPixelFormat
    {
        Unknown = -1,
        None = Interop.AVPixelFormat.AV_PIX_FMT_NONE,
        YUV420P = Interop.AVPixelFormat.AV_PIX_FMT_YUV420P,
        YUYV422 = Interop.AVPixelFormat.AV_PIX_FMT_YUYV422,
        RGB24 = Interop.AVPixelFormat.AV_PIX_FMT_RGB24,
        BGR24 = Interop.AVPixelFormat.AV_PIX_FMT_BGR24,
        YUV422P = Interop.AVPixelFormat.AV_PIX_FMT_YUV422P,
        YUV444P = Interop.AVPixelFormat.AV_PIX_FMT_YUV444P,
        YUV410P = Interop.AVPixelFormat.AV_PIX_FMT_YUV410P,
        YUV411P = Interop.AVPixelFormat.AV_PIX_FMT_YUV411P,
        GRAY8 = Interop.AVPixelFormat.AV_PIX_FMT_GRAY8,
        MONOWHITE = Interop.AVPixelFormat.AV_PIX_FMT_MONOWHITE,
        MONOBLACK = Interop.AVPixelFormat.AV_PIX_FMT_MONOBLACK,
        PAL8 = Interop.AVPixelFormat.AV_PIX_FMT_PAL8,
        YUVJ420P = Interop.AVPixelFormat.AV_PIX_FMT_YUVJ420P,
        YUVJ422P = Interop.AVPixelFormat.AV_PIX_FMT_YUVJ422P,
        YUVJ444P = Interop.AVPixelFormat.AV_PIX_FMT_YUVJ444P,
        UYVY422 = Interop.AVPixelFormat.AV_PIX_FMT_UYVY422,
        UYYVYY411 = Interop.AVPixelFormat.AV_PIX_FMT_UYYVYY411,
        BGR8 = Interop.AVPixelFormat.AV_PIX_FMT_BGR8,
        BGR4 = Interop.AVPixelFormat.AV_PIX_FMT_BGR4,
        BGR4_BYTE = Interop.AVPixelFormat.AV_PIX_FMT_BGR4_BYTE,
        RGB8 = Interop.AVPixelFormat.AV_PIX_FMT_RGB8,
        RGB4 = Interop.AVPixelFormat.AV_PIX_FMT_RGB4,
        RGB4_BYTE = Interop.AVPixelFormat.AV_PIX_FMT_RGB4_BYTE,
        NV12 = Interop.AVPixelFormat.AV_PIX_FMT_NV12,
        NV21 = Interop.AVPixelFormat.AV_PIX_FMT_NV21,
        ARGB = Interop.AVPixelFormat.AV_PIX_FMT_ARGB,
        RGBA = Interop.AVPixelFormat.AV_PIX_FMT_RGBA,
        ABGR = Interop.AVPixelFormat.AV_PIX_FMT_ABGR,
        BGRA = Interop.AVPixelFormat.AV_PIX_FMT_BGRA,
        GRAY16BE = Interop.AVPixelFormat.AV_PIX_FMT_GRAY16BE,
        GRAY16LE = Interop.AVPixelFormat.AV_PIX_FMT_GRAY16LE,
        YUV440P = Interop.AVPixelFormat.AV_PIX_FMT_YUV440P,
        YUVJ440P = Interop.AVPixelFormat.AV_PIX_FMT_YUVJ440P,
        YUVA420P = Interop.AVPixelFormat.AV_PIX_FMT_YUVA420P,
        RGB48BE = Interop.AVPixelFormat.AV_PIX_FMT_RGB48BE,
        RGB48LE = Interop.AVPixelFormat.AV_PIX_FMT_RGB48LE,
        RGB565BE = Interop.AVPixelFormat.AV_PIX_FMT_RGB565BE,
        RGB565LE = Interop.AVPixelFormat.AV_PIX_FMT_RGB565LE,
        RGB555BE = Interop.AVPixelFormat.AV_PIX_FMT_RGB555BE,
        RGB555LE = Interop.AVPixelFormat.AV_PIX_FMT_RGB555LE,
        BGR565BE = Interop.AVPixelFormat.AV_PIX_FMT_BGR565BE,
        BGR565LE = Interop.AVPixelFormat.AV_PIX_FMT_BGR565LE,
        BGR555BE = Interop.AVPixelFormat.AV_PIX_FMT_BGR555BE,
        BGR555LE = Interop.AVPixelFormat.AV_PIX_FMT_BGR555LE,
        VAAPI_MOCO = Interop.AVPixelFormat.AV_PIX_FMT_VAAPI_MOCO,
        VAAPI_IDCT = Interop.AVPixelFormat.AV_PIX_FMT_VAAPI_IDCT,
        VAAPI_VLD = Interop.AVPixelFormat.AV_PIX_FMT_VAAPI_VLD,
        VAAPI = Interop.AVPixelFormat.AV_PIX_FMT_VAAPI,
        YUV420P16LE = Interop.AVPixelFormat.AV_PIX_FMT_YUV420P16LE,
        YUV420P16BE = Interop.AVPixelFormat.AV_PIX_FMT_YUV420P16BE,
        YUV422P16LE = Interop.AVPixelFormat.AV_PIX_FMT_YUV422P16LE,
        YUV422P16BE = Interop.AVPixelFormat.AV_PIX_FMT_YUV422P16BE,
        YUV444P16LE = Interop.AVPixelFormat.AV_PIX_FMT_YUV444P16LE,
        YUV444P16BE = Interop.AVPixelFormat.AV_PIX_FMT_YUV444P16BE,
        DXVA2_VLD = Interop.AVPixelFormat.AV_PIX_FMT_DXVA2_VLD,
        RGB444LE = Interop.AVPixelFormat.AV_PIX_FMT_RGB444LE,
        RGB444BE = Interop.AVPixelFormat.AV_PIX_FMT_RGB444BE,
        BGR444LE = Interop.AVPixelFormat.AV_PIX_FMT_BGR444LE,
        BGR444BE = Interop.AVPixelFormat.AV_PIX_FMT_BGR444BE,
        YA8 = Interop.AVPixelFormat.AV_PIX_FMT_YA8,
        Y400A = Interop.AVPixelFormat.AV_PIX_FMT_Y400A,
        GRAY8A = Interop.AVPixelFormat.AV_PIX_FMT_GRAY8A,
        BGR48BE = Interop.AVPixelFormat.AV_PIX_FMT_BGR48BE,
        BGR48LE = Interop.AVPixelFormat.AV_PIX_FMT_BGR48LE,
        YUV420P9BE = Interop.AVPixelFormat.AV_PIX_FMT_YUV420P9BE,
        YUV420P9LE = Interop.AVPixelFormat.AV_PIX_FMT_YUV420P9LE,
        YUV420P10BE = Interop.AVPixelFormat.AV_PIX_FMT_YUV420P10BE,
        YUV420P10LE = Interop.AVPixelFormat.AV_PIX_FMT_YUV420P10LE,
        YUV422P10BE = Interop.AVPixelFormat.AV_PIX_FMT_YUV422P10BE,
        YUV422P10LE = Interop.AVPixelFormat.AV_PIX_FMT_YUV422P10LE,
        YUV444P9BE = Interop.AVPixelFormat.AV_PIX_FMT_YUV444P9BE,
        YUV444P9LE = Interop.AVPixelFormat.AV_PIX_FMT_YUV444P9LE,
        YUV444P10BE = Interop.AVPixelFormat.AV_PIX_FMT_YUV444P10BE,
        YUV444P10LE = Interop.AVPixelFormat.AV_PIX_FMT_YUV444P10LE,
        YUV422P9BE = Interop.AVPixelFormat.AV_PIX_FMT_YUV422P9BE,
        YUV422P9LE = Interop.AVPixelFormat.AV_PIX_FMT_YUV422P9LE,
        GBRP = Interop.AVPixelFormat.AV_PIX_FMT_GBRP,
        GBR24P = Interop.AVPixelFormat.AV_PIX_FMT_GBR24P,
        GBRP9BE = Interop.AVPixelFormat.AV_PIX_FMT_GBRP9BE,
        GBRP9LE = Interop.AVPixelFormat.AV_PIX_FMT_GBRP9LE,
        GBRP10BE = Interop.AVPixelFormat.AV_PIX_FMT_GBRP10BE,
        GBRP10LE = Interop.AVPixelFormat.AV_PIX_FMT_GBRP10LE,
        GBRP16BE = Interop.AVPixelFormat.AV_PIX_FMT_GBRP16BE,
        GBRP16LE = Interop.AVPixelFormat.AV_PIX_FMT_GBRP16LE,
        YUVA422P = Interop.AVPixelFormat.AV_PIX_FMT_YUVA422P,
        YUVA444P = Interop.AVPixelFormat.AV_PIX_FMT_YUVA444P,
        YUVA420P9BE = Interop.AVPixelFormat.AV_PIX_FMT_YUVA420P9BE,
        YUVA420P9LE = Interop.AVPixelFormat.AV_PIX_FMT_YUVA420P9LE,
        YUVA422P9BE = Interop.AVPixelFormat.AV_PIX_FMT_YUVA422P9BE,
        YUVA422P9LE = Interop.AVPixelFormat.AV_PIX_FMT_YUVA422P9LE,
        YUVA444P9BE = Interop.AVPixelFormat.AV_PIX_FMT_YUVA444P9BE,
        YUVA444P9LE = Interop.AVPixelFormat.AV_PIX_FMT_YUVA444P9LE,
        YUVA420P10BE = Interop.AVPixelFormat.AV_PIX_FMT_YUVA420P10BE,
        YUVA420P10LE = Interop.AVPixelFormat.AV_PIX_FMT_YUVA420P10LE,
        YUVA422P10BE = Interop.AVPixelFormat.AV_PIX_FMT_YUVA422P10BE,
        YUVA422P10LE = Interop.AVPixelFormat.AV_PIX_FMT_YUVA422P10LE,
        YUVA444P10BE = Interop.AVPixelFormat.AV_PIX_FMT_YUVA444P10BE,
        YUVA444P10LE = Interop.AVPixelFormat.AV_PIX_FMT_YUVA444P10LE,
        YUVA420P16BE = Interop.AVPixelFormat.AV_PIX_FMT_YUVA420P16BE,
        YUVA420P16LE = Interop.AVPixelFormat.AV_PIX_FMT_YUVA420P16LE,
        YUVA422P16BE = Interop.AVPixelFormat.AV_PIX_FMT_YUVA422P16BE,
        YUVA422P16LE = Interop.AVPixelFormat.AV_PIX_FMT_YUVA422P16LE,
        YUVA444P16BE = Interop.AVPixelFormat.AV_PIX_FMT_YUVA444P16BE,
        YUVA444P16LE = Interop.AVPixelFormat.AV_PIX_FMT_YUVA444P16LE,
        VDPAU = Interop.AVPixelFormat.AV_PIX_FMT_VDPAU,
        XYZ12LE = Interop.AVPixelFormat.AV_PIX_FMT_XYZ12LE,
        XYZ12BE = Interop.AVPixelFormat.AV_PIX_FMT_XYZ12BE,
        NV16 = Interop.AVPixelFormat.AV_PIX_FMT_NV16,
        NV20LE = Interop.AVPixelFormat.AV_PIX_FMT_NV20LE,
        NV20BE = Interop.AVPixelFormat.AV_PIX_FMT_NV20BE,
        RGBA64BE = Interop.AVPixelFormat.AV_PIX_FMT_RGBA64BE,
        RGBA64LE = Interop.AVPixelFormat.AV_PIX_FMT_RGBA64LE,
        BGRA64BE = Interop.AVPixelFormat.AV_PIX_FMT_BGRA64BE,
        BGRA64LE = Interop.AVPixelFormat.AV_PIX_FMT_BGRA64LE,
        YVYU422 = Interop.AVPixelFormat.AV_PIX_FMT_YVYU422,
        YA16BE = Interop.AVPixelFormat.AV_PIX_FMT_YA16BE,
        YA16LE = Interop.AVPixelFormat.AV_PIX_FMT_YA16LE,
        GBRAP = Interop.AVPixelFormat.AV_PIX_FMT_GBRAP,
        GBRAP16BE = Interop.AVPixelFormat.AV_PIX_FMT_GBRAP16BE,
        GBRAP16LE = Interop.AVPixelFormat.AV_PIX_FMT_GBRAP16LE,
        QSV = Interop.AVPixelFormat.AV_PIX_FMT_QSV,
        MMAL = Interop.AVPixelFormat.AV_PIX_FMT_MMAL,
        D3D11VA_VLD = Interop.AVPixelFormat.AV_PIX_FMT_D3D11VA_VLD,
        CUDA = Interop.AVPixelFormat.AV_PIX_FMT_CUDA,
        XRGB = Interop.AVPixelFormat.AV_PIX_FMT_0RGB,
        RGB0 = Interop.AVPixelFormat.AV_PIX_FMT_RGB0,
        XBGR = Interop.AVPixelFormat.AV_PIX_FMT_0BGR,
        BGR0 = Interop.AVPixelFormat.AV_PIX_FMT_BGR0,
        YUV420P12BE = Interop.AVPixelFormat.AV_PIX_FMT_YUV420P12BE,
        YUV420P12LE = Interop.AVPixelFormat.AV_PIX_FMT_YUV420P12LE,
        YUV420P14BE = Interop.AVPixelFormat.AV_PIX_FMT_YUV420P14BE,
        YUV420P14LE = Interop.AVPixelFormat.AV_PIX_FMT_YUV420P14LE,
        YUV422P12BE = Interop.AVPixelFormat.AV_PIX_FMT_YUV422P12BE,
        YUV422P12LE = Interop.AVPixelFormat.AV_PIX_FMT_YUV422P12LE,
        YUV422P14BE = Interop.AVPixelFormat.AV_PIX_FMT_YUV422P14BE,
        YUV422P14LE = Interop.AVPixelFormat.AV_PIX_FMT_YUV422P14LE,
        YUV444P12BE = Interop.AVPixelFormat.AV_PIX_FMT_YUV444P12BE,
        YUV444P12LE = Interop.AVPixelFormat.AV_PIX_FMT_YUV444P12LE,
        YUV444P14BE = Interop.AVPixelFormat.AV_PIX_FMT_YUV444P14BE,
        YUV444P14LE = Interop.AVPixelFormat.AV_PIX_FMT_YUV444P14LE,
        GBRP12BE = Interop.AVPixelFormat.AV_PIX_FMT_GBRP12BE,
        GBRP12LE = Interop.AVPixelFormat.AV_PIX_FMT_GBRP12LE,
        GBRP14BE = Interop.AVPixelFormat.AV_PIX_FMT_GBRP14BE,
        GBRP14LE = Interop.AVPixelFormat.AV_PIX_FMT_GBRP14LE,
        YUVJ411P = Interop.AVPixelFormat.AV_PIX_FMT_YUVJ411P,
        BAYER_BGGR8 = Interop.AVPixelFormat.AV_PIX_FMT_BAYER_BGGR8,
        BAYER_RGGB8 = Interop.AVPixelFormat.AV_PIX_FMT_BAYER_RGGB8,
        BAYER_GBRG8 = Interop.AVPixelFormat.AV_PIX_FMT_BAYER_GBRG8,
        BAYER_GRBG8 = Interop.AVPixelFormat.AV_PIX_FMT_BAYER_GRBG8,
        BAYER_BGGR16LE = Interop.AVPixelFormat.AV_PIX_FMT_BAYER_BGGR16LE,
        BAYER_BGGR16BE = Interop.AVPixelFormat.AV_PIX_FMT_BAYER_BGGR16BE,
        BAYER_RGGB16LE = Interop.AVPixelFormat.AV_PIX_FMT_BAYER_RGGB16LE,
        BAYER_RGGB16BE = Interop.AVPixelFormat.AV_PIX_FMT_BAYER_RGGB16BE,
        BAYER_GBRG16LE = Interop.AVPixelFormat.AV_PIX_FMT_BAYER_GBRG16LE,
        BAYER_GBRG16BE = Interop.AVPixelFormat.AV_PIX_FMT_BAYER_GBRG16BE,
        BAYER_GRBG16LE = Interop.AVPixelFormat.AV_PIX_FMT_BAYER_GRBG16LE,
        BAYER_GRBG16BE = Interop.AVPixelFormat.AV_PIX_FMT_BAYER_GRBG16BE,
        XVMC = Interop.AVPixelFormat.AV_PIX_FMT_XVMC,
        YUV440P10LE = Interop.AVPixelFormat.AV_PIX_FMT_YUV440P10LE,
        YUV440P10BE = Interop.AVPixelFormat.AV_PIX_FMT_YUV440P10BE,
        YUV440P12LE = Interop.AVPixelFormat.AV_PIX_FMT_YUV440P12LE,
        YUV440P12BE = Interop.AVPixelFormat.AV_PIX_FMT_YUV440P12BE,
        AYUV64LE = Interop.AVPixelFormat.AV_PIX_FMT_AYUV64LE,
        AYUV64BE = Interop.AVPixelFormat.AV_PIX_FMT_AYUV64BE,
        VIDEOTOOLBOX = Interop.AVPixelFormat.AV_PIX_FMT_VIDEOTOOLBOX,
        P010LE = Interop.AVPixelFormat.AV_PIX_FMT_P010LE,
        P010BE = Interop.AVPixelFormat.AV_PIX_FMT_P010BE,
        GBRAP12BE = Interop.AVPixelFormat.AV_PIX_FMT_GBRAP12BE,
        GBRAP12LE = Interop.AVPixelFormat.AV_PIX_FMT_GBRAP12LE,
        GBRAP10BE = Interop.AVPixelFormat.AV_PIX_FMT_GBRAP10BE,
        GBRAP10LE = Interop.AVPixelFormat.AV_PIX_FMT_GBRAP10LE,
        MEDIACODEC = Interop.AVPixelFormat.AV_PIX_FMT_MEDIACODEC,
        GRAY12BE = Interop.AVPixelFormat.AV_PIX_FMT_GRAY12BE,
        GRAY12LE = Interop.AVPixelFormat.AV_PIX_FMT_GRAY12LE,
        GRAY10BE = Interop.AVPixelFormat.AV_PIX_FMT_GRAY10BE,
        GRAY10LE = Interop.AVPixelFormat.AV_PIX_FMT_GRAY10LE,
        P016LE = Interop.AVPixelFormat.AV_PIX_FMT_P016LE,
        P016BE = Interop.AVPixelFormat.AV_PIX_FMT_P016BE,
        D3D11 = Interop.AVPixelFormat.AV_PIX_FMT_D3D11,
        GRAY9BE = Interop.AVPixelFormat.AV_PIX_FMT_GRAY9BE,
        GRAY9LE = Interop.AVPixelFormat.AV_PIX_FMT_GRAY9LE,
        GBRPF32BE = Interop.AVPixelFormat.AV_PIX_FMT_GBRPF32BE,
        GBRPF32LE = Interop.AVPixelFormat.AV_PIX_FMT_GBRPF32LE,
        GBRAPF32BE = Interop.AVPixelFormat.AV_PIX_FMT_GBRAPF32BE,
        GBRAPF32LE = Interop.AVPixelFormat.AV_PIX_FMT_GBRAPF32LE,
        DRM_PRIME = Interop.AVPixelFormat.AV_PIX_FMT_DRM_PRIME,
        OPENCL = Interop.AVPixelFormat.AV_PIX_FMT_OPENCL,
        GRAY14BE = Interop.AVPixelFormat.AV_PIX_FMT_GRAY14BE,
        GRAY14LE = Interop.AVPixelFormat.AV_PIX_FMT_GRAY14LE,
        GRAYF32BE = Interop.AVPixelFormat.AV_PIX_FMT_GRAYF32BE,
        GRAYF32LE = Interop.AVPixelFormat.AV_PIX_FMT_GRAYF32LE,
        YUVA422P12BE = Interop.AVPixelFormat.AV_PIX_FMT_YUVA422P12BE,
        YUVA422P12LE = Interop.AVPixelFormat.AV_PIX_FMT_YUVA422P12LE,
        YUVA444P12BE = Interop.AVPixelFormat.AV_PIX_FMT_YUVA444P12BE,
        YUVA444P12LE = Interop.AVPixelFormat.AV_PIX_FMT_YUVA444P12LE,
        NV24 = Interop.AVPixelFormat.AV_PIX_FMT_NV24,
        NV42 = Interop.AVPixelFormat.AV_PIX_FMT_NV42,
        VULKAN = Interop.AVPixelFormat.AV_PIX_FMT_VULKAN,
        Y210BE = Interop.AVPixelFormat.AV_PIX_FMT_Y210BE,
        Y210LE = Interop.AVPixelFormat.AV_PIX_FMT_Y210LE,
        X2RGB10LE = Interop.AVPixelFormat.AV_PIX_FMT_X2RGB10LE,
        X2RGB10BE = Interop.AVPixelFormat.AV_PIX_FMT_X2RGB10BE,
    }
}
