name: nugetize-ffmpeg

on: workflow_dispatch

jobs:
  build-nuget:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
    - run: .\scripts\nugetize-ffmpeg.cmd
      shell: cmd
    - uses: actions/upload-artifact@v2
      with:
        name: dependencies
        path: .\artifacts\pkg\**\*
        if-no-files-found: error
  publish-nightlies-azure:
    runs-on: ubuntu-latest
    needs: [ build-nuget ]
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: dependencies
        path: ./artifacts
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        source-url: https://pkgs.dev.azure.com/ronaldvanmanen/_packaging/ronaldvanmanen/nuget/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.AZURE_DEVOPS_PAT }}
    - run: dotnet nuget push "./artifacts/**/*.nupkg" --api-key AzureDevOps --skip-duplicate
  publish-nightlies-github:
    runs-on: ubuntu-latest
    needs: [ build-nuget ]
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: dependencies
        path: ./artifacts
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        source-url: https://nuget.pkg.github.com/ronaldvanmanen/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: dotnet nuget push "./artifacts/**/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
